### ISSUE TITLE
Error detected while processing function <SNR>139_on_exit[6]..<SNR>139_ExtractLinewise[2]..vista#parser#ctags#FromExtendedRaw[28]..<SNR>151_LoadData: when writing ~/.aliases file

### ISSUE THREAD

**Issue by alichtman** [liuchengxu/vista.vim#207] opened 2019-12-15 05:05 UTC
**Describe the bug**

The following error is shown when writing and opening `~/.aliases`. I can not reproduce it on any other file. Frankly, I have no idea what's going on.

I haven't opened the Vista buffer, although it works properly for other files (`~/.zshrc`, for example).

```
Error detected while processing function <SNR>139_on_exit[6]..<SNR>139_ExtractLinewise[2]..vista#parser#ctags#FromExtendedRaw[28]..<SNR>151_LoadData:
line   15:
E716: Key not present in Dictionary: line, 'text': line.name }
```

**Environment:**
- OS: `macOS 10.14.6`
- Vim/Neovim version: `NVIM v0.4.3 Build type: Release`
- This plugin version: `c1b976faa6c1e0ad6ad70604ff0b8d4b2ce626f7`

**Vista info**

Here's the output of `:Vista info`.

```
    Current FileType: zsh
Avaliable Executives: ['coc', 'ctags']
    Global Variables:
    let g:vista#executive#ctags#support_json_format = 0
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'nvim_lsp', 'vim_lsc', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista#renderer#enable_icon = 1
    let g:vista_fzf_preview = ['right:50%']
    let g:vista_icon_indent = ['╰─▸ ', '├─▸ ']
```

**Steps to reproduce given the above info**

1. Open ~/.aliases
2. Observe errors

I honestly don't expect this bug to be reproducible, so I'm just hoping a developer has some idea as to what could be going wrong.

**Expected behavior**

No error to be displayed when opening the file.

**Actual behavior**

An error is displayed when opening the file.

**Screenshot or gif** (if possible)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/20600565/70858343-bed03a80-1f00-11ea-8a03-3a1a9106de9c.png">

**Solution**

The only solution I have at the moment is uninstalling the plugin.

**Comment by liuchengxu** [comment] 2019-12-15 05:17
I have tried your https://github.com/alichtman/dotfiles/blob/master/.aliases, seeing no error. Can you provide the sample file to reproduce?

**Comment by alichtman** [comment] 2019-12-15 05:21
Yeah, it's exactly that file. I wasn't expecting it to be reproducible, as I can't even reproduce it on any other file. So I'm thinking it's something to do with my system configuration.

Have any ideas for what I should start poking around at?

**Comment by liuchengxu** [comment] 2019-12-15 05:37
Closing then. Feel free to reopen if you can reproduce with a minimal vimrc.

**Closed by liuchengxu** 2019-12-15 05:37 UTC
Labels: bug

**Comment by alichtman** [comment] 2019-12-15 05:39
Thanks for looking into this with me. Cheers 🍻

**Comment by wren** [comment] 2020-08-27 22:55
Hi, I just ran into this same thing and tracked it down to one of my aliases: 
```sh
alias rmds="find . -depth -name .DS_Store -exec rm {} \;"
```

The funny part is that the error doesn't come up if I change the double quotes to single quotes (`"` to `'`). After some poking around, it looks like a semicolon inside of double quotes in the zsh filetype that emits this error.

I can repro this reliably with this file:
```sh
alias foo=";"
```

And fix it reliably with:
```sh
alias foo=';'
```

And a quick glance at [@alichtman's aliases](https://github.com/alichtman/dotfiles/blob/master/.config/zsh/.aliases), shows there's at least one alias with a semicolon enclosed in double quotes, so I think that was probably the same issue.

Hope this helps someone!

**Comment by wren** [comment] 2020-08-27 22:57
Oh, there was also a small confounding factor in that I have [airline](https://github.com/vim-airline/vim-airline) installed. It automatically detects vista and integrates with it (which is why the the error happens when opening the file). You can disable the vista integration in airline with `let g:airline#extensions#vista#enabled = 0` in your vimrc (probably on for zsh files). But even without airline, the error comes up when I invoke vista on that same file above, so this definitely seems like a vista issue.

**Comment by alichtman** [comment] 2020-09-06 08:54
@wren, I am seriously impressed that you were able to explain this behavior. I'll make this fix to my dots and hopefully it'll solve the problem.

**Comment by wren** [comment] 2020-09-07 02:47
@alichtman No worries. Happy to help!

I have to admit that--when tracking down an off-the-wall error in that requires a set of very specific, admittedly rare conditions--I didn't expect to run into an issue filed by someone I know.

I guess the open-source world can be a really small place sometimes. 😆

**Comment by kuntau** [comment] 2020-09-13 19:43
Thanks @wren 

Weird that I've just noticed this today. My aliases haven't changed for a while.

Made some test. Not all `;` in double quote give problem

This is ok.
```zsh
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"
```

While this make Vista freaked out, even though it's in single quote 🤔 
```zsh
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'
```

**Comment by liuchengxu** [comment] 2020-09-13 22:59
Since a lot of people had this issue, maybe it's worthy of making https://github.com/liuchengxu/vista.vim/blob/013f2d0060/autoload/vista/parser/ctags.vim#L94 more robust? The another solution is to recompile your ctags for the JSON support https://github.com/liuchengxu/vista.vim#compile-ctags-with-json-format-support, then you won't run into this IMO.
