### ISSUE TITLE
The cursor tag highlight does not work when first time entering the vista sidebar

### ISSUE THREAD

**Issue by rahulsalvi** [liuchengxu/vista.vim#292] opened 2020-05-18 08:59 UTC
**Describe the bug**
When first launching :Vista coc, vista creates a new buffer with name ```__vista__```. vista#source#Update is then called on the new buffer instead of the source file, so LSP functions might not work. Closing the Vista buffer with q then opening it again makes Vista work normally.

**Environment:**
- OS: Linux 5.6.13
- Vim/Neovim version:
NVIM v0.4.3
Build type: Release
- This plugin version:
3061f117579608f4e0e62d8d46ecadcbbc920fd8
- I'm using some LSP client:
    - coc
    - The Vim LSP client version:
9704f8d076426177dcbd92067dc76bafa266f852
    - Have you tried updated to the latest version of this LSP client: N/A

**Vista info**

```    

    Current FileType: text
Avaliable Executives: ['coc']
    Global Variables:
    let g:vista = {'get_tagline_under_cursor': function('18'), 'winnr': function('16'), 'source': {'fname': '', 'bufnr': 1, 'get_winid': function('20'), 'winid': 1000, 'winnr': 1, 'extension': function('25'), 'line': function('23'), 'get_winnr': function('19'), 'filetype': function('21'), 'lines': function('22'), 'line_trimmed': function('24'), 'scope_seperator': function('26'), 'fpath': ''}, 'winid': function('17')}
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'nvim_lsp', 'vim_lsc', 'vim_lsp']
    let g:vista#extensions = ['markdown', 'rst']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista_blink = [2, 100]
    let g:vista_close_on_jump = 0
    let g:vista_cursor_delay = 400
    let g:vista_default_executive = 'ctags'
    let g:vista_disable_statusline = 1
    let g:vista_echo_cursor = 1
    let g:vista_executive_for = {}
    let g:vista_find_absolute_nearest_method_or_function = 0
    let g:vista_find_nearest_method_or_function_delay = 300
    let g:vista_fold_toggle_icons = ['▼', '▶']
    let g:vista_icon_indent = ['└ ', '│ ']
    let g:vista_ignore_kinds = []
    let g:vista_no_mappings = 0
    let g:vista_sidebar_position = 'vertical botright'
    let g:vista_sidebar_width = 30
    let g:vista_stay_on_open = 1
    let g:vista_top_level_blink = [2, 100]
    let g:vista_update_on_text_changed = 0
    let g:vista_update_on_text_changed_delay = 500
```

**Steps to reproduce given the above info**

minimal vimrc (neccessary when this issue is about some Vim LSP client):

```vim
set nocompatible
set runtimepath^=/path/to/vista.vim
syntax on
filetype plugin indent on
```

1. Open a file with a configured language server
2. Enter command ```:Vista coc``` (language server features do not work, filename at the top is ```/path/to/source/file/__vista__```)
3. Press q (default to close Vista buffer, but does not call vista#sidebar#Close)
4. Enter command :Vista coc again (language server features do work, filename at the top is correct)

I tested using coc with MPLS and CCLS and got similar results with both.

**Expected behavior**
Launching Vista works the first time

**Actual behavior**
Launching Vista works the first time. The following fixes the issue for me at least, but in a "nasty hack" sort of way:
```
diff --git a/autoload/vista/source.vim b/autoload/vista/source.vim
index 6e1a01f..f66e8f1 100644
--- a/autoload/vista/source.vim
+++ b/autoload/vista/source.vim
@@ -39,6 +39,12 @@ function! vista#source#Update(bufnr, winnr, ...) abort
     call vista#init#Api()
   endif
 
+  if a:0 > 0
+    if stridx(a:1, '__vista__') != -1
+        return
+    endif
+  endif
+
   let g:vista.source.bufnr = a:bufnr
   let g:vista.source.winnr = a:winnr
 ```
This works by not updating the current source file if it has contains the string ```__vista__```

**Screenshot or gif** (if possible)

**Comment by liuchengxu** [comment] 2020-07-15 00:38
I can't reproduce on the latest master, feel free to reopen if you still see it with the latest master.

BTW vista.vim now has a logging feature for debugging purpose, see `:h g:vista_log_file`. You can inject some logging info to see which part is not functional.

**Comment by rahulsalvi** [comment] 2020-09-17 00:24
I still experience this issue, but I can be a bit more clear in what the problem is. Launching vista for the first time will show all of the symbols in the file, but hovering over a symbol doesn't highlight it and you can't jump to it with enter.  The root of the problem seems to be that at some point vista#source#Update gets called with parameters pointing to the vista sidebar instead of an actual source code buffer. 

In the attached screenshots, I am hovering over the lock_ptr field in the vista sidebar. The first screenshot is the first time I launched vista. You can see that the filename in the top right ends with "vista" instead of the actual filename and nothing is highlighted. In the second screenshot, the filename (futex.c) is correct and hovering works as expected (lock_ptr is highlighted and pressing enter will jump to it).

First time launching vista sidebar:
![first_launch](https://user-images.githubusercontent.com/1747204/93404990-9df69600-f840-11ea-8647-0f7592b2225b.png)
Second time:
![second_launch](https://user-images.githubusercontent.com/1747204/93404992-9e8f2c80-f840-11ea-86ff-acb381713623.png)

Another fix is to set g:vista_stay_on_open=0 so that the current buffer is set correctly when entering the vista sidebar.

**Comment by liuchengxu** [comment] 2020-09-17 00:40
Reopened, but I recently don't have time to debug it, hoping someone can give a hand on this.

**Comment by liuchengxu** [comment] 2020-11-21 07:52
Seemingly this has be resolved in the latest master. Let me know if it still persists.

**Closed by liuchengxu** 2020-11-21 07:52 UTC
Labels: PR welcome

**Comment by rahulsalvi** [comment] 2020-11-21 21:33
Unfortunately, this doesn't seem to be fixed for me. The filename shown is now relative to compile_commands.json, but the issue where __vista__ appears instead of the actual file still occurs. For what it's worth, I've been using the workaround from my original post for a while and I haven't seen any negative consequences.

**Comment by liuchengxu** [comment] 2020-11-22 00:16
@rahulsalvi Hmm, I can't reproduce it now. Please provide the minimal vimrc and steps for reproduction If you still want me to look into this :(.
