### ISSUE TITLE
No tags displayed for 'pcd_io.cpp'

### ISSUE THREAD

**Issue by linjiX** [liuchengxu/vista.vim#184] opened 2019-11-21 03:35 UTC
**Describe the bug**
Use Vista for file [pcd_io.cpp](https://github.com/PointCloudLibrary/pcl/blob/master/io/src/pcd_io.cpp)
No tags displayed.

**Environment:**
- OS: macOS
- Vim/Neovim version: NVIM v0.4.3
- This plugin version: 44ad0dab12a92c0ee530941f1349d3814a551696

**Vista info**
```
    Current FileType: vista
Avaliable Executives: ['ctags']
    Global Variables:
    let g:vista#executive#ctags#support_json_format = 1
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsc', 'vim_lsp']
    let g:vista#finders = ['fzf', 'skim']
    let g:vista#renderer#ctags = 'default'
    let g:vista#renderer#default#vlnum_offset = 3
    let g:vista#renderer#enable_icon = 1
    let g:vista#renderer#icons = {'subroutine': '羚', 'method': '', 'func': '', 'variables': '', 'namespace': '', 'field': '', 'interface': '', 'type': '', 'packages': '', 'property': ' ', 'implementation': '', 'default': '', 'augroup': 'פּ', 'macro': '', 'enumerator': '
', 'const': '', 'macros': '', 'map': 'פּ', 'fields': '', 'functions': '', 'enum': '', 'function': '', 'target': '', 'typedef': '', 'variable': '', 'modules': '', 'constant': '', 'struct': '', 'types': '', 'module': '', 'typeParameter': '', 'package': '', 'class': '',
 'member': '', 'var': '', 'union': '鬒'}
    let g:vista#renderer#kind_default_icon = ['╰─▸ ', '├─▸ ']
    let g:vista_fold_toggle_icons = ['▼', '▶']
```

**Steps to reproduce given the above info**

1. Open file [pcd_io.cpp](https://github.com/PointCloudLibrary/pcl/blob/master/io/src/pcd_io.cpp) by Neovim
2. `:Vista`

**Expected behavior**
The tags of this file should appear in the Vista window.

**Actual behavior**
Only the file name appears in the Vista window.
No tags appear.

**Screenshot or gif** (if possible)
Vista on the left, tagbar on the right
![screenshot](https://user-images.githubusercontent.com/46097255/69299852-9ed49080-0c4c-11ea-8d00-b88d6b719a35.png)

**Comment by liuchengxu** [comment] 2019-11-21 04:29
Related to #123 . I believe it's a fundamental design flow of vista's ctags renderer as mentioned in https://github.com/liuchengxu/vista.vim/issues/123#issuecomment-552620940 . It may not be fixed for a long time in that I don't have enough time for it currently.

**Comment by liuchengxu** [comment] 2020-03-25 06:51
Closing as duplicate of #123.

**Closed by liuchengxu** 2020-03-25 06:51 UTC
Labels: ctags, help wanted :raised_hands:, tree view
