### ISSUE TITLE
Alignment lines are disrupted by Vista

### ISSUE THREAD

**Issue by JarodLi** [liuchengxu/vista.vim#178] opened 2019-11-12 13:42 UTC
**Describe the bug**
If position on the left, alignment lines are disrupted(screenshot 1) ; 
if positon on the right,  character appears  in the leftmost column(screenshot 2)

**Environment:**
- OS: Centos-7
- Vim/Neovim version: NVIM v0.5.0-137-g93626b8af
- This plugin version: latest

**Vista info**

```
Current FileType: python                                                                                                                                                                
Avaliable Executives: ['ctags', 'vim_lsp']                                                                                                                                                  
    Global Variables:                                                                                                                                                                       
    let g:vista#executive#ctags#support_json_format = 1                                                                                                                                     
    let g:vista#executives = ['ale', 'coc', 'ctags', 'lcn', 'vim_lsc', 'vim_lsp']                                                                                                           
    let g:vista#finders = ['fzf', 'skim']                                                                                                                                                   
    let g:vista#renderer#ctags = 'default'                                                                                                                                                  
    let g:vista#renderer#default#vlnum_offset = 3                                                                                                                                           
    let g:vista#renderer#enable_icon = 1                                                                                                                                                    
    let g:vista#renderer#icons = {'subroutine': '羚', 'method': '', 'func': '', 'variables': '', 'namespace': '', 'field': '', 'interface': '', 'type': '', 'packages': '', y': '襁', 'implementation': '', 'default': '', 'augroup': 'פּ', 'macro': '', 'enumerator': '', 'const': '', 'macros': '', 'map': 'פּ', 'fields': '', 'functions': '', 'enum': nction': '', 'target': '', 'typedef': '', 'variable': '', 'modules': '', 'constant': '', 'struct': '', 'types': '', 'module': '', 'typeParameter': '', 'package': '', ', 'member': '', 'var': '', 'union': '鬒'}                                                                                                                                                  let g:vista_fold_toggle_icons = ['▼', '▶']                                                                                                                                                  let g:vista_sidebar_position = 'vertical topleft'  
```

**Steps to reproduce given the above info**

1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshot or gif** (if possible)

![截图](https://user-images.githubusercontent.com/3362590/68675306-8f8d7d00-0592-11ea-9618-ec5bfa7efd7e.JPG)

![截图](https://user-images.githubusercontent.com/3362590/68675981-feb7a100-0593-11ea-823d-92aa2d5f1a8b.JPG)

**Comment by liuchengxu** [comment] 2019-11-12 15:16
Can you also provide a minimal vimrc and steps to reproduce? I can't quite understand.

**Comment by JarodLi** [comment] 2019-11-16 03:59
minimal vimrc: 
```
call plug#begin('~/.vim/bundle')                                                                                                                                                            
Plug 'liuchengxu/vista.vim'                                                                                                                                                                 
call plug#end()                                                                                                                                                                             
                                                                                                                                                                                            
nmap <leader>tlv :Vista!!<CR>                                                                                                                                                               
let g:vista_sidebar_position = 'vertical topleft'                                                                                                                                           
autocmd FileType vista nnoremap <buffer> q :call vista#sidebar#Close()<CR>
```   
steps: 
1. open one py file  with nvim  
2. :Vista  
![截图](https://user-images.githubusercontent.com/3362590/68987803-7d4c6100-0868-11ea-9148-1ac4b1de7931.PNG)

3. switch to right window(code window)  
4.  'j' to move down  
5. The alignment lines between vista window and code window break off     
![image](https://user-images.githubusercontent.com/3362590/68987809-86d5c900-0868-11ea-8fe1-4dd132dd09ef.png)

**Comment by JarodLi** [comment] 2019-11-16 10:42
I login my centos with xshell, I'm not sure if this issue is related to xshell.

**Comment by liuchengxu** [comment] 2019-11-16 14:13
Can't reproduce.

**Comment by JarodLi** [comment] 2019-11-25 03:42
I replace xshell with putty, the issue above disappear! 
But, there is a special character after class name, could you tell me how to fix it?
![image](https://user-images.githubusercontent.com/3362590/69510552-64cefb80-0f78-11ea-8b84-1ae3b2315165.png)

**Comment by liuchengxu** [comment] 2019-11-25 03:44
`let g:vista#renderer#enable_icon  = 0`, closing then.

**Closed by liuchengxu** 2019-11-25 03:44 UTC
Labels: can't reproduce

**Comment by JarodLi** [comment] 2019-11-25 03:49
Thanks a lot!
